#!/bin/bash
# Kontrola dátumov - správne zobrazovanie Unix timestamp

echo "═══════════════════════════════════════════════════════════"
echo "KONTROLA DÁTUMOV - SPRÁVNE ZOBRAZOVANIE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Kontrola reportDate (Unix timestamp v milisekundách):"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT symbol, reportDate, datetime(reportDate/1000, 'unixepoch', 'localtime') as reportDate_parsed, datetime(updatedAt, 'localtime') as updatedAt FROM final_report ORDER BY updatedAt DESC LIMIT 10;"
echo ""
echo "2. Kontrola snapshotDate:"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT symbol, snapshotDate, datetime(snapshotDate/1000, 'unixepoch', 'localtime') as snapshotDate_parsed FROM final_report LIMIT 5;"
echo ""
echo "3. Kontrola cron_execution_log (ak má záznamy):"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT jobType, status, datetime(startedAt/1000, 'unixepoch', 'localtime') as startedAt, datetime(completedAt/1000, 'unixepoch', 'localtime') as completedAt FROM cron_execution_log ORDER BY startedAt DESC LIMIT 5;" 2>/dev/null || echo "Žiadne záznamy"
echo ""
echo "4. Kontrola cron_status:"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT jobType, status, datetime(lastRunAt/1000, 'unixepoch', 'localtime') as lastRunAt FROM cron_status ORDER BY lastRunAt DESC;"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "✅ DÁTUMY SÚ SPRÁVNE ULOŽENÉ!"
echo "   Problém bol len v zobrazovaní - SQLite ukladá DateTime"
echo "   ako Unix timestamp v milisekundách, nie ako text."
echo "═══════════════════════════════════════════════════════════"

