#!/bin/bash
# Finálna kontrola stavu aplikácie

echo "═══════════════════════════════════════════════════════════"
echo "FINÁLNA KONTROLA STAVU APLIKÁCIE"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. STATUS SERVICES:"
echo "───────────────────────────────────────────────────────────"
systemctl status earnings-table --no-pager -l | head -12
echo ""
systemctl status earnings-cron --no-pager -l | head -12
echo ""
echo "2. POSLEDNÉ LOGY EARNINGS-CRON (20 riadkov):"
echo "───────────────────────────────────────────────────────────"
journalctl -u earnings-cron -n 20 --no-pager | tail -15
echo ""
echo "3. DATÁUMY V FINAL_REPORT (prvých 10 záznamov):"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT symbol, date(reportDate) as reportDate, datetime(updatedAt, 'localtime') as updatedAt FROM final_report ORDER BY updatedAt DESC LIMIT 10;"
echo ""
echo "4. LOGY V CRON_EXECUTION_LOG (posledných 10 záznamov):"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT jobType, status, datetime(startedAt, 'localtime') as startedAt, datetime(completedAt, 'localtime') as completedAt, recordsProcessed FROM cron_execution_log ORDER BY startedAt DESC LIMIT 10;"
echo ""
echo "5. CRON STATUS (aktuálny stav):"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT jobType, status, datetime(lastRunAt, 'localtime') as lastRunAt, recordsProcessed FROM cron_status ORDER BY lastRunAt DESC;"
echo ""
echo "6. POČET ZÁZNAMOV V TABUĽKÁCH:"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT 'finnhub_data' as table_name, COUNT(*) as count FROM finnhub_data UNION ALL SELECT 'polygon_data', COUNT(*) FROM polygon_data UNION ALL SELECT 'final_report', COUNT(*) FROM final_report UNION ALL SELECT 'cron_execution_log', COUNT(*) FROM cron_execution_log UNION ALL SELECT 'cron_status', COUNT(*) FROM cron_status;"
echo ""
echo "7. KONTROLA DÁTUMOV V FINNHUB_DATA (prvých 5 záznamov):"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT symbol, date(reportDate) as reportDate, datetime(updatedAt, 'localtime') as updatedAt FROM finnhub_data ORDER BY updatedAt DESC LIMIT 5;"
echo ""
echo "8. API ENDPOINT TEST:"
echo "───────────────────────────────────────────────────────────"
curl -s http://localhost:5555/api/final-report | jq '. | length' 2>/dev/null && echo " records returned" || echo "API endpoint check failed"
echo ""
echo "═══════════════════════════════════════════════════════════"

