#!/bin/bash
# Diagnostika prečo sa dátumy neaktualizujú

echo "═══════════════════════════════════════════════════════════"
echo "DIAGNOSTIKA: PREČO SA DÁTUMY NEAKTUALIZUJÚ"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Kontrola či pipeline bežal po vymazaní:"
echo "───────────────────────────────────────────────────────────"
journalctl -u earnings-cron --since "10 minutes ago" --no-pager | grep -E "Pipeline|generateFinalReport|reportDate|updatedAt" | tail -20
echo ""
echo "2. Kontrola finnhub_data - reportDate:"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT symbol, date(reportDate) as reportDate, datetime(updatedAt, 'localtime') as updatedAt FROM finnhub_data ORDER BY updatedAt DESC LIMIT 5;"
echo ""
echo "3. Kontrola final_report - všetky dátumy:"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT symbol, date(reportDate) as reportDate, date(snapshotDate) as snapshotDate, datetime(updatedAt, 'localtime') as updatedAt, datetime(createdAt, 'localtime') as createdAt FROM final_report LIMIT 5;"
echo ""
echo "4. Kontrola raw hodnoty reportDate v final_report:"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT symbol, reportDate, typeof(reportDate) as type FROM final_report LIMIT 5;"
echo ""
echo "5. Kontrola cron_execution_log:"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT jobType, status, datetime(startedAt, 'localtime') as startedAt, datetime(completedAt, 'localtime') as completedAt FROM cron_execution_log ORDER BY startedAt DESC LIMIT 5;"
echo ""
echo "6. Kontrola cron_status:"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT jobType, status, datetime(lastRunAt, 'localtime') as lastRunAt FROM cron_status ORDER BY lastRunAt DESC;"
echo ""
echo "7. Posledných 30 riadkov logov (hľadanie chýb):"
echo "───────────────────────────────────────────────────────────"
journalctl -u earnings-cron -n 30 --no-pager | tail -20
echo ""
echo "═══════════════════════════════════════════════════════════"

