#!/bin/bash
# Kontrola po vymazaní starých záznamov

echo "═══════════════════════════════════════════════════════════"
echo "KONTROLA PO VYMAZANÍ STARÝCH ZÁZNAMOV"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Kontrola či sa záznamy vymazali:"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT COUNT(*) as 'cron_execution_log (2000-01-01)' FROM cron_execution_log WHERE date(startedAt) = '2000-01-01';"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT COUNT(*) as 'cron_status (2000-01-01)' FROM cron_status WHERE date(lastRunAt) = '2000-01-01';"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT COUNT(*) as 'final_report (2000-01-01)' FROM final_report WHERE date(reportDate) = '2000-01-01';"
echo ""
echo "2. Reštart earnings-cron:"
echo "───────────────────────────────────────────────────────────"
systemctl restart earnings-cron && sleep 8 && echo "✅ Service reštartovaný"
echo ""
echo "3. Status service:"
echo "───────────────────────────────────────────────────────────"
systemctl status earnings-cron --no-pager -l | head -15
echo ""
echo "4. Posledných 15 riadkov logov:"
echo "───────────────────────────────────────────────────────────"
journalctl -u earnings-cron -n 15 --no-pager | tail -10
echo ""
echo "5. Aktuálny stav dátumov (počkaj 5-10 min na pipeline):"
echo "───────────────────────────────────────────────────────────"
sqlite3 -header -column modules/database/prisma/prod.db "SELECT symbol, date(reportDate) as reportDate, datetime(updatedAt, 'localtime') as updatedAt FROM final_report ORDER BY updatedAt DESC LIMIT 5;"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "💡 Počkaj 5-10 minút na ďalšie spustenie pipeline a potom"
echo "   skontroluj dátumy znova pomocou:"
echo "   sqlite3 -header -column modules/database/prisma/prod.db \"SELECT symbol, date(reportDate) as reportDate, datetime(updatedAt, 'localtime') as updatedAt FROM final_report ORDER BY updatedAt DESC LIMIT 5;\""
echo "═══════════════════════════════════════════════════════════"

